[package]
name = "rugroll"
version = "0.1.0"
description = "RugRoll: Provably-fair crash game on MagicBlock Ephemeral Rollups"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "rugroll"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "=1.0.2", features = ["init-if-needed"] }
anchor-spl = { version = "=1.0.2" }
ephemeral-rollups-sdk = { version = "0.16.2", features = ["anchor", "access-control"] }
ephemeral-vrf-sdk = { version = "0.17.0", features = ["anchor"] }

[dev-dependencies]
anchor-client = "0.31.0"
